M48
; DRILL file {KiCad 5.99.0-unknown-293f207356~131~ubuntu20.04.1} date Fri Jul 30 20:50:08 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-07-30T20:50:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-293f207356~131~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
%
G90
G05
T1
X11.525Y37.031
X15.525Y37.031
T0
M30
